#!/bin/bash
FILE=/tmp/mail$$
cat > $FILE
trap "/bin/rm -f $FILE" 0 1 2 3 13 15

if [[ "${1}" == "learn_spam" ]]; then
  cat ${FILE} | /usr/bin/curl -s --data-binary @- http://rspamd:11334/learnspam
  cat ${FILE} | /usr/bin/curl -H "Flag: 11" -s --data-binary @- http://rspamd:11334/fuzzyadd
elif [[ "${1}" == "learn_ham" ]]; then
  cat ${FILE} | /usr/bin/curl -s --data-binary @- http://rspamd:11334/learnham
  cat ${FILE} | /usr/bin/curl -H "Flag: 13" -s --data-binary @- http://rspamd:11334/fuzzyadd
fi